### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by everyoneknowsthat** [yogwoggf/gelly#30] opened 2024-06-04 10:36 UTC
### GPU

gtx 1650

### Operating System

windows 11

### Is this specific to performance?

- [ ] Yes
- [x] No

### Issue Type

Other

### Incident Description

the liquid falls through the floor and sometimes it just freezes and wont move and is stuck on me screen

**Comment by yogwoggf** [comment] 2024-06-06 04:45
Duplicate of #33

**Closed by yogwoggf** 2024-06-06 04:45 UTC
Labels: incorrect behavior, rendering, bug, critical
